// added git again...
const products = [
  {
    book_id: "1",
    title: "Clean Code: A Handbook of Agile Software Craftsmanship",
    image: "/images/clean_code_book.jpg",
    description:
      "Noted software expert Robert C. Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship. Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer―but only if you work at it.",
    author: "Robert C. Martin",
    genre: "Programming",
    price: 784,
    numOfPages: 464,
    countInStock: 10,
    rating: 4.6,
    numReviews: 12,
    language: "English",
    ISBN: 9132350884,
    weight: "732 g",
    dimensions: "17.65 x 3.18 x 23.37 cm",
  },
  {
    book_id: "2",
    title: "Let Us C: Authentic Guide to C PROGRAMMING Language",
    image: "/images/let_us_c.jpg",
    description:
      "The new edition of this classic book has been thoroughly revamped, but remains faithful to the principles that have established it as a favourite amongst students, teachers and software professionals round the world. “Simplicity”- that has been the hallmark of this book in not only its previous sixteen English editions, but also in the Hindi, gujrati, Japanese, Korean, Chinese and us editions. This book doesn't assume any programming background. It begins with the basics and steadily builds the pace so that the reader finds it easy to handle advanced topics towards the end of the book.",
    author: "Yashavant Kanetkar",
    genre: "Programming",
    price: 275,
    numOfPages: 486,
    countInStock: 15,
    rating: 4.5,
    numReviews: 25,
    language: "English",
    ISBN: 9389845688,
    weight: "837 g",
    dimensions: "17.78 x 2.79 x 25.4 cm",
  },
  {
    book_id: "3",
    title: "Introduction to Algorithms",
    image: "/images/introduction_to_algo.jpg",
    description:
      "This internationally acclaimed textbook provides a comprehensive introduction to the modern study of computer algorithms. It covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers. Each chapter is relatively selfcontained and presents an algorithm, a design technique, an application area, or a related topic. The algorithms are described and designed in a manner to be readable by anyone who has done a little programming. The explanations have been kept elementary without sacrificing depth of coverage or mathematical rigor.",
    author: "Thomas H. Cormen",
    genre: "Programming",
    price: 765,
    numOfPages: 1312,
    countInStock: 8,
    rating: 3.5,
    numReviews: 22,
    language: "English",
    ISBN: 9413350865,
    weight: "1 kg 810 g",
    dimensions: "27.5 x 21 x 3 cm",
  },
  {
    book_id: "4",
    title: "The Collected Poems (Harper Perennial Modern Classics)",
    image: "/images/the_collected_poems.jpg",
    description:
      "By the time of her death on 11, February 1963, Sylvia Plath had written a large bulk of poetry. To my knowledge, she never scrapped any of her poetic efforts. With one or two exceptions, she brought every piece she worked on to some final form acceptable to her, rejecting at most the odd verse, or a false head or a false tail. Her attitude to her verse was artisan-like: if she couldn’t get a table out of the material, she was quite happy to get a chair, or even a toy. The end product for her was not so much a successful poem, as something that had temporarily exhausted her ingenuity. So this book contains not merely what verse she saved, but—after 1956—all she wrote.—Ted Hughes, from the Introduction",
    author: "Sylvia Plath",
    genre: "Poetry",
    price: 1325,
    numOfPages: 384,
    countInStock: 5,
    rating: 4.7,
    numReviews: 35,
    language: "English",
    ISBN: 9961558893,
    weight: "445 g",
    dimensions: "2.79 x 15.49 x 23.11 cm",
  },
  {
    book_id: "5",
    title: "Life of Pi: Booker Prize Winner 2002",
    image: "/images/life_of_pi.jpg",
    description:
      "Yann Martel's Life of Pi is a transformative novel, an astonishing work of imagination that will delight and stun readers in equal measure. It is a triumph of storytelling and a tale that will, as one character puts it, make you believe in God. After the tragic sinking of a cargo ship, a solitary lifeboat remains bobbing on the wide, wild Pacific. The crew of the surviving vessel consists of a hyena, one zebra (with broken leg), an orang-utan, a 450-pound Royal Bengal Tiger named Richard Parker and Pi - a 16-year-old Indian boy. As the 'crew' begin to assert their natural places in the food chain, Pi's fear mounts, and he must use all his wit and daring to develop an understanding with Richard the tiger. Life of Pi takes the reader on an extraordinary journey - geographical, spiritual and emotional. A rare thing, here is a novel that will change your view of the world.",
    author: "Yann Martel",
    genre: "Action and adventure",
    price: 195,
    numOfPages: 352,
    countInStock: 18,
    rating: 4.3,
    numReviews: 26,
    language: "English",
    ISBN: 9780857865,
    weight: "236 g",
    dimensions: "12.9 x 2.1 x 19.8 cm",
  },
  {
    book_id: "6",
    title: "To Kill A Mockingbird: 60th Anniversary Edition",
    image: "/images/to_kill_a_mockingbird.jpg",
    description:
      "A lawyer's advice to his children as he defends the real mockingbird of Harper Lee's classic novel - a black man falsely charged with the rape of a white girl. Through the young eyes of Scout and Jem Finch, Harper Lee explores with exuberant humour the irrationality of adult attitudes to race and class in the Deep South of the 1930s. The conscience of a town steeped in prejudice, violence and hypocrisy is pricked by the stamina of one man's struggle for justice. But the weight of history will only tolerate so much.",
    author: "Harper Lee",
    genre: "Classics",
    price: 257,
    numOfPages: 320,
    countInStock: 16,
    rating: 4.6,
    numReviews: 12,
    language: "English",
    ISBN: 9780099549,
    weight: "171 g",
    dimensions: "10.3 x 2.1 x 17.6 cm",
  },
];

export default products;
